### To build:
# docker build -f Dockerfile-arango-b -t ingenium/arangodb:3.9.3b .
### To publish
# docker tag ingenium/arangodb:3.9.3b artifactory.jpl.nasa.gov:16003/gov/nasa/jpl/ingenium/arangodb:3.9.3b
# docker push artifactory.jpl.nasa.gov:16003/gov/nasa/jpl/ingenium/arangodb:3.9.3b
FROM arangodb/arangodb:3.9.3
COPY arangod-b.conf /etc/arangodb3/arangod.conf
